services:

  nginx:
    image: nginx:alpine
    container_name: web-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/errors:/usr/share/nginx/html/errors
    depends_on:
      - app1
      - app2
    networks:
      - web_network

  app1:
    build:
      context: ./backend/app1
    container_name: backend-app1
    expose:
      - "3000"
    networks:
      - web_network

  app2:
    build:
      context: ./backend/app2
    container_name: backend-app2
    expose:
      - "3000"
    networks:
      - web_network

  ubuntu-server:
    build:
      context: ./ubuntu-server
    container_name: ubuntu-server
    hostname: ubuntu-server
    stdin_open: true
    tty: true
    networks:
      - web_network

networks:
  web_network:
    driver: bridge