server {
    listen 80 default_server;
    server_name _;
    default_type text/plain;
    include /etc/nginx/conf.d/snippets/errors.conf;

    location / {
        return 200 "Nginx funcionando correctamente\n";
    }
}
